In [1]:
import tensorflow as tf

In [17]:
# 张量限幅
# clip_by_value; 
a=tf.range(10)
print('a:',a.numpy())

print(tf.maximum(a,2).numpy())
print(tf.minimum(a,8).numpy())

print(tf.clip_by_value(a,2,8).numpy())


a: [0 1 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 8]
[2 2 2 3 4 5 6 7 8 8]


In [29]:
# clip_by_norm
a=tf.random.normal([2,2],mean=10)
print(a.numpy())
print(tf.norm(a).numpy())

aa=tf.clip_by_norm(a,15)
print(aa.numpy())

print(tf.norm(aa).numpy())

[[ 8.74183   9.817571]
 [ 9.996708 11.386528]]
20.059698
[[6.53686   7.341265 ]
 [7.4752183 8.514481 ]]
14.999999


In [ ]:
# gradient clipping
#new_grads,total_norm=tf.clip_by_global_norm(grads,25)

In [ ]:
(x,y),_ = datasets.mnist.load_data()
x=tf.convert_to_tensor(x,dtype=tf.float32)/50




