In [1]:
import tensorflow as tf

In [4]:
# where,
a=tf.random.normal([3,3])
print(a.numpy())
mask=a>0
print(mask.numpy())

a_=tf.boolean_mask(a,mask)
print(a_.numpy())

indices=tf.where(mask)
print('indices:',indices.numpy())

a_positive=tf.gather_nd(a,indices)
print(a_positive.numpy())

[[ 0.6720385  -0.01031734 -0.03729183]
 [-0.04012383  1.3340611  -2.3645973 ]
 [-0.03031069 -0.54227346  0.5382785 ]]
[[ True False False]
 [False  True False]
 [False False  True]]
[0.6720385 1.3340611 0.5382785]
indices: [[0 0]
 [1 1]
 [2 2]]
[0.6720385 1.3340611 0.5382785]


In [6]:
#scatter_nd, meshgrid
indices=tf.constant([[4],[3],[1],[7]])
updata=tf.constant([9,10,11,12])
shape=tf.constant([8])

tf.scatter_nd(indices, updata,shape)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 0, 11,  0, 10,  9,  0,  0, 12])>