In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a=tf.constant(1.0)
print(a.device)
a=tf.identity(a,'gpu')
print(a.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0


In [12]:
c=tf.constant([True,False])
print('c.dtype=',c.dtype)
print('tf.is_tensor()=',tf.is_tensor(c))
c.dtype==tf.bool

c.dtype= <dtype: 'bool'>
tf.is_tensor()= True


True

In [15]:
d=np.arange(5)
print('d.dtype=',d.dtype)
dd=tf.convert_to_tensor(d)
print('dd.dtype=',dd.dtype)
ddd=tf.convert_to_tensor(d,dtype=tf.float64)
print('ddd.dtype=',ddd.dtype)

d.dtype= int32
dd.dtype= <dtype: 'int32'>
ddd.dtype= <dtype: 'float64'>


In [21]:
a=np.arange(5)
tf.cast(a,dtype=tf.float32)
tf.cast(a,dtype=tf.float64)
tf.cast(a,dtype=tf.int32)
tf.cast(a,dtype=tf.bool)

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True,  True,  True,  True])>

In [23]:
a=tf.range(5)
b=tf.Variable(a)
b.trainable

True

In [27]:
a.numpy()

array([0, 1, 2, 3, 4])

In [28]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [29]:
tf.convert_to_tensor([1,2.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [30]:
tf.convert_to_tensor([[1],[2]])

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]])>

In [35]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [37]:
tf.zeros_like(a)
tf.zeros(a.shape)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [39]:
tf.fill([2,2],1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

In [40]:
tf.random.normal([2,2],mean=1,stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.5723331, 1.4134262],
       [0.6472379, 2.1119113]], dtype=float32)>

In [41]:
tf.random.truncated_normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.3063698 ,  0.26256087],
       [ 0.7084333 ,  0.23856452]], dtype=float32)>

In [42]:
tf.random.uniform([2,3],minval=1,maxval=2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.2198126, 1.734729 , 1.7678044],
       [1.0254551, 1.6346661, 1.9379026]], dtype=float32)>

In [44]:
idx=tf.range(64)
idx=tf.random.shuffle(idx)
idx

<tf.Tensor: shape=(64,), dtype=int32, numpy=
array([29, 43, 11,  7, 52, 24, 45, 15, 56, 58, 62, 28, 30, 10, 61, 57, 60,
       44,  3, 51, 21, 48, 33,  6, 22, 23, 46, 18, 38,  0, 31,  1, 17, 36,
       34, 27, 25, 40, 16, 47,  9, 37, 54, 42, 55, 20, 41, 32, 49, 63, 13,
       59, 12, 53, 14, 35,  8,  4, 50,  2, 39, 19, 26,  5])>

In [57]:
y=tf.range(4)
y=tf.one_hot(y,depth=5)
y

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [59]:
out=tf.random.uniform([4,5])
loss=tf.keras.losses.mse(y,out)
loss

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.46767187, 0.4568084 , 0.28909093, 0.53645134], dtype=float32)>

In [60]:
loss=tf.reduce_mean(loss)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.43750563>

In [62]:
a=tf.ones([1,5,5,3])
a

<tf.Tensor: shape=(1, 5, 5, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

In [65]:
a[0][1][1][0]


<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [3]:
a=tf.random.normal([4,3,2,1])
a.shape

TensorShape([4, 3, 2, 1])

In [5]:
tf.transpose(a,perm=[0,2,1,3]).shape

TensorShape([4, 2, 3, 1])

In [6]:
tf.expand_dims(a,axis=0).shape

TensorShape([1, 4, 3, 2, 1])

In [9]:
tf.squeeze(a,axis=3).shape

TensorShape([4, 3, 2])

In [11]:
# tensor 的运算
a=tf.ones([2,2])
b=tf.fill([2,2],3.0)

# 元素级别的+ -，* /
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)

tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-2. -2.]
 [-2. -2.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3. 3.]
 [3. 3.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.33333334 0.33333334]
 [0.33333334 0.33333334]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [12]:
print(tf.math.log(a))
print(tf.exp(a))

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2.7182817 2.7182817]
 [2.7182817 2.7182817]], shape=(2, 2), dtype=float32)


In [16]:
print(tf.pow(b,3))
print(b**2)
print(tf.sqrt(b))

tf.Tensor(
[[27. 27.]
 [27. 27.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[9. 9.]
 [9. 9.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.7320508 1.7320508]
 [1.7320508 1.7320508]], shape=(2, 2), dtype=float32)


In [18]:
print(a@b)
print(tf.matmul(a,b))

tf.Tensor(
[[6. 6.]
 [6. 6.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[6. 6.]
 [6. 6.]], shape=(2, 2), dtype=float32)
