In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # 仅打印error
import tensorflow as tf

In [ ]:
# tf.norm(ord=1,axis=0);
# tf.reduce_min,tf.reduce_max,tf.reduce_sum, tf.reduce_mean
# tf.concat([],axis)
# tf.split()
# tf.stack()
# tf.unstack()

# tf.argmax(); tf.argmin()
# tf.gather(uniquevalue, idx=[])


In [9]:
# 排序
# tf.sort; tf.argsort()
# tf.math.top_k(a,k)
a=tf.random.shuffle(tf.range(5))
print(a)
print(tf.sort(a, direction='DESCENDING'))
print(tf.argsort(a,direction='DESCENDING'))

idx=tf.argsort(a,direction='DESCENDING')
print(tf.gather(a, idx))

res=tf.math.top_k(a,2)
print(res.values)
print(res.indices)

tf.Tensor([2 3 0 1 4], shape=(5,), dtype=int32)
tf.Tensor([4 3 2 1 0], shape=(5,), dtype=int32)
tf.Tensor([4 1 0 3 2], shape=(5,), dtype=int32)
tf.Tensor([4 3 2 1 0], shape=(5,), dtype=int32)
tf.Tensor([4 3], shape=(2,), dtype=int32)
tf.Tensor([4 1], shape=(2,), dtype=int32)


In [8]:
# top k accuracy
def accuracy (output, target,topk=(1,)):
    maxk=max(topk)
    batch_size=target.shape[0]
    
    pred= tf.math.top_k(output,maxk).indices
    pred= tf.transpose(pred,perm=[1,0])
    
    target_=tf.broadcast_to(target,pred.shape)
    correct=tf.equal(pred,target_)
    
    res=[]
    for k in topk:
        correct_k = tf.cast(tf.reshape(correct[:k],[-1]),dtype=tf.float32)
        correct_k = tf.reduce_sum(correct_k)
        acc=float(100*correct_k/batch_size)
        res.append(acc)
        
    return res

In [9]:
output=tf.random.normal([10,6])
output = tf.math.softmax(output,axis=1)
target=tf.random.uniform([10],maxval=6,dtype=tf.int32)

print('prob:',output.numpy())

pred= tf.argmax(output,axis=1)
print('pred:',pred.numpy())
print('label:',target.numpy())

acc=accuracy(output,target,topk=(1,2,3,4,5,6))
print('top1-4 acc:',acc)

prob: [[0.34058818 0.08478226 0.3542981  0.14553182 0.05255574 0.02224393]
 [0.2578358  0.10143638 0.06435652 0.08376305 0.14919016 0.34341815]
 [0.11798612 0.27782145 0.2726635  0.15347153 0.01416239 0.16389506]
 [0.19310333 0.18103242 0.09105074 0.08183169 0.05066606 0.4023158 ]
 [0.10631447 0.13052502 0.17966488 0.12458062 0.3916076  0.06730731]
 [0.06607252 0.26831734 0.00527319 0.04529761 0.07752501 0.5375143 ]
 [0.6052705  0.101074   0.17439076 0.02986377 0.05504066 0.03436027]
 [0.12916143 0.04967189 0.13414986 0.3338912  0.21397844 0.13914713]
 [0.4398982  0.08674557 0.13879223 0.24607497 0.05675685 0.0317322 ]
 [0.11418805 0.29575384 0.06104372 0.12794892 0.21328953 0.18777592]]
pred: [2 5 1 5 4 5 0 3 0 1]
label: [3 1 1 0 0 1 1 5 4 1]
top1-4 acc: [20.0, 40.0, 70.0, 80.0, 100.0, 100.0]
